data:
  csv_path: t1_third_approach/data/rc4_dataset.csv
  output_dir: t1_third_approach/artifacts
  split:
    train: 0.7
    eval: 0.2
    infer: 0.1
  use_sos_eos: true # Add start and end tokens to the sequences
  n: 20000
  min_len: 16
  max_len: 32
  key: 'secretkey'

train:
  epochs: 30
  lr: 0.001
  device: 'auto' # "cuda" | "cpu" | "auto"
  grad_clip: 1.0
  num_workers: 2
  batch_size: 64
  vocab_size: 257 # ASCII (256) + <pad>
  weight_decay: 0.0005
  print_every: 1

validation:
  loss_threshold: 1.5
  acc_threshold: 0.7

model:
  embedding_dim: 128
  hidden_dim: 256
  max_len: 64 # for the output layer
