data:
  csv_path: second_approach/data/cesar_dataset.csv
  output_dir: artifacts
  train_split: 0.9
  use_sos_eos: false

vocab:
  min_freq: 1
  fixed_chars: 'abcdefghijklmnopqrstuvwxyz'
  add_tokens: ['<pad>', '<sos>', '<eos>']

loader:
  batch_size: 64
  num_workers: 2
  pin_memory: true

model:
  emb_dim: 64
  hidden_dim: 128
  tie_embeddings: false

train:
  epochs: 100
  lr: 0.001
  teacher_forcing: 0.5
  device: 'auto' # "cuda" | "cpu" | "auto"
  grad_clip: 1.0
  ckpt_every: 1

eval:
  max_batches: null # o número para evaluación rápida

infer:
  max_len: null # si null, usa la del dataset
  strategy: 'greedy' # "greedy" | "beam"
  beam_size: 4
